#!/usr/bin/env sh
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')

# run linter on staged files
echo "Running Rubocop"

bundle exec rubocop --config .rubocop.yml --parallel --force-exclusion  -a $STAGED_FILES
RUBOCOP_EXIT_CODE=$?

# add files auto-fixed by the rubocop
git add -f $STAGED_FILES

# check linter exit code
if [ $RUBOCOP_EXIT_CODE -ne 0 ]; then
    echo "!!! Fix rubocop warnings before commit"
    exit 1
else
    echo "Rubocop checks are passed"
fi

# run audit related to staged files
# echo "Running Security Audit"
# ./bin/audit
# AUDIT_EXIT_CODE=$?

# # check rspec exit code
# if [ $AUDIT_EXIT_CODE -ne 0 ]; then
#     echo "!!! Fix potential vulnerabilities before commit"
#     exit 1
# else
#     echo "Audit checks are passed"
# fi

# # run tests related to staged files
echo "Running RSpec tests"
bundle exec rspec
RSPEC_EXIT_CODE=$?

# check rspec exit code
if [ $RSPEC_EXIT_CODE -ne 0 ]; then
    echo "!!! Fix spec fails before commit"
    exit 1
else
    echo "Specs are passed"
fi

# return 0-exit code
echo "Pre commit checks are passed"
exit 0
